
---
- name: Tasks to create a zone RR AAAA type in TCPWave IPAM
  hosts: localhost
  vars:
    user_cert_file: /opt/ansible/keys/ansible.crt
    user_cert_key_file: /opt/ansible/keys/ansible.key
    ipam_ip: 10.1.10.120
    organization_name: Dunkin
    zone_name: test.in
    owner_name: ARecord
    data: 2001:0db8:85a3:0000:0000:8a2e:0370:7334

  tasks:
    - name: Create a Zone RR AAAA type
      uri:
        url: 'https://{{ ipam_ip }}:7443/tims/rest/zone/rr/add'
        client_cert: '{{ user_cert_file }}'
        client_key: '{{ user_cert_key_file }}'
        method: POST
        headers:
          Content-Type: application/json
        body: {
               
                        'zoneName': '{{ zone_name }}',
                        'owner': '{{owner_name}}',
                        'rrclass': 'IN',
                        'rrtype': 'AAAA',
                        'ttl': '1200',
                        'data': '{{data}}',
                        'description': '',
                        'is_external_rr': 0,
                        'status': 1,
                        'organization_name': '{{ organization_name }}'
              }
        status_code: 204
        body_format: json
        validate_certs: no
