---
- name: Tasks to create a object RR NAPTR type in TCPWave IPAM
  hosts: localhost
  vars:
    user_cert_file: /opt/ansible/keys/ansible.crt
    user_cert_key_file: /opt/ansible/keys/ansible.key
    ipam_ip: 10.1.10.120
    organization_name: Dunkin
    owner: NAPTR
    data: 100 100 U E2U+si example.com.
    ip: 1.0.0.9

  tasks:
    - name: Create a Object RR NAPTR type
      uri:
        url: 'https://{{ ipam_ip }}:7443/tims/rest/object/rr/add'
        client_cert: '{{ user_cert_file }}'
        client_key: '{{ user_cert_key_file }}'
        method: POST
        headers:
          Content-Type: application/json
        body: {
                        'owner': '{{ owner }}',
                        'rrclass': 'IN',
                        'rrtype': 'NAPTR',
                        'ttl': 1200,
                        'data': '{{ data }}',
                        'ipAddr': '{{ ip }}',
                        'is_ad_rr': 0,
                        'organization_name': '{{ organization_name }}'
        }
        status_code: 200
        body_format: json
        validate_certs: no
